### ISSUE TITLE
UpdateMonitor() uses a different but similar "monitor" object compared to other Monitor functions

### ISSUE THREAD

**Issue by tonglil** [DataDog/datadog-api-client-go#1012]
**Describe the bug**
User is expected to transform datadog.Monitor into datadog.MonitorUpdateRequest manually between `GetMonitor` and `UpdateMonitor` or `ValidateMonitor`, when they are nearly the identical type. Why not just let the use of datadog.Monitor?

https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/model_monitor.go#L18
https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/model_monitor_update_request.go#L17

All use `monitor`
https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/api_monitors.go#L710
https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/api_monitors.go#L344
https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/api_monitors.go#L1713

But this one is different for some reason?
https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/api_monitors.go#L1536

For SyntheticsAPI, that's what you do: datadog.SyntheticsAPITest is used for get, create, and update.
https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/api_synthetics.go#L1283
https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/api_synthetics.go#L349
https://github.com/DataDog/datadog-api-client-go/blob/v1.1.0/api/v1/datadog/api_synthetics.go#L3309

**Expected behavior**
All use the same type, so that a `get` call can be followed by a `update` call without copying every field over manually..

**Comment by therve** [comment]
Hi,

We define different objects to be able to make backward compatible changes to update requests without changing all signatures. Ultimately in v2 the pattern tends to go to have a different object in every calls for that purpose.

In that particular case, there are indeed identical so you should be able to use golang conversion to go from a `Monitor` to a `MonitorUpdateRequest`. Let us know if that doesn't work for you, thanks.
