### ISSUE TITLE
`DashboardsApi.GetDashboard()` returns error "Required field height missing"

### ISSUE THREAD

**Issue by bin3377** [DataDog/datadog-api-client-go#1032]
**Describe the bug**
Using function DashboardsApi.GetDashboard() to query a new flow style dashboard. For some cases (especially after dragging the groups in 2-column mode) response is 200 but giving an error "Required field height missing".

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
1. Create a new style dashboard
2. Create multiple groups
3. Drag groups in high-density mode into 2nd column
4. Save the dashboard and query it with DashboardsApi.GetDashboard() API error returned besides HTTP 200 response
5. By looking the json in response body, the layout of one widget is `"layout":{"is_column_break":true},`, which missing x/y/height/width

**Expected behavior**
dashboard queried out

**Screenshots**

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - version for this project in use.
  - services, libraries, languages and tools list and versions.

**Additional context**

**Comment by therve** [comment]
Hi! This should have been fixed in the backend, let us know if you're still encountering the issue. Thanks!
