### ISSUE TITLE
Add support for distribution_points endpoint to submit distribution metrics

### ISSUE THREAD

**Issue by afarbos** [DataDog/datadog-api-client-go#1127]
I would like to be able to create distribution metrics using the golang API, however the client today only support count, rate and gauge.

Adding support for https://api.datadoghq.com/api/v1/distribution_points to submit distribution metrics, example in [the python client ](https://github.com/DataDog/datadogpy/blob/v0.42.0/datadog/api/distributions.py)

**Comment by therve** [comment]
Fixed in #1518 , wll be in the next release. Thanks!
