### ISSUE TITLE
Synthetics - IsCritical missing on SyntheticsStep

### ISSUE THREAD

**Issue by mattbartel-tyler** [DataDog/datadog-api-client-go#1323]
[SyntheticsStep](https://github.com/DataDog/datadog-api-client-go/blob/6b5328a6b852a5c794d92aba7615e7f4db9da027/api/v1/datadog/model_synthetics_step.go#L16) doesn't have `IsCritical` even though the API is returning this value (compared to [SyntheticsApiStep](https://github.com/DataDog/datadog-api-client-go/blob/6b5328a6b852a5c794d92aba7615e7f4db9da027/api/v1/datadog/model_synthetics_api_step.go#L25) which does).

**Expected behavior**

`IsCritical' should be available on both API and browser tests.

**Environment and Versions (please complete the following information):**

Version 1.8.0

**Comment by therve** [comment]
Thanks for your report, should be fixed by #1327.
