### ISSUE TITLE
Please add example to authenticate using application key, and api key

### ISSUE THREAD

**Issue by sunshine69** [DataDog/datadog-api-client-go#1338]
**Note:**
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It is not clear how I authenticate the golang api client with datadog.

To save time please add an example of how to authenticate.
I read from some site and trying to export various attempt the env var without success.  The java api sdk has some example about authentication though, but not golang.

**Describe alternatives you've considered**

**Additional context**

**Comment by therve** [comment]
Hi,

The getting started doc has an example which should cover it. Here's the section containing the authentication:

```go
    ctx := context.WithValue(
        context.Background(),
        datadog.ContextAPIKeys,
        map[string]datadog.APIKey{
            "apiKeyAuth": {
                Key: os.Getenv("DD_CLIENT_API_KEY"),
            },
            "appKeyAuth": {
                Key: os.Getenv("DD_CLIENT_APP_KEY"),
            },
        },
    )
```.

**Comment by sunshine69** [comment]
Sorry I just found in the doc, let me try, thanks for your response and my apologies for mis-read.
