### ISSUE TITLE
error-tracking alert cannot be parsed

### ISSUE THREAD

**Issue by winebarrel** [DataDog/datadog-api-client-go#1383]
**Describe the bug**

I get the following error when importing error-tracking alerts in terraform-provider-datadog.

```
$ terraform import datadog_monitor.my_monitor 123456789
│ Error: object contains unparsed element: map[created:2022-03-14T03:14:44.712215+00:00 created_at:1.647227684e+12 creator:map[email:xxx@xxx handle:xxx@xxx id:xxx name:genki SUGAWARA] deleted:<nil> id:xxx message:@xxx modified:2022-03-14T04:33:12.454800+00:00 multi:true name:test {{[@issue.id].name}} options:map[enable_logs_sample:true escalation_message: groupby_simple_monitor:false include_tags:true new_host_delay:300 notify_audit:false notify_no_data:false restriction_query:<nil> silenced:map[] thresholds:map[critical:1]] org_id:xxx overall_state:No Data overall_state_modified:2022-03-14T03:18:48+00:00 priority:<nil> query:error-tracking-traces("env:staging @issue.age:<=300000").rollup("count").by("@issue.id").last("5m") > 1 restricted_roles:<nil> tags:[] type:error-tracking alert]
```

This appears to be due to the fact that datadog-api-client-go does not support error-tracking alerts.

https://github.com/DataDog/terraform-provider-datadog/blob/ada5d0ffa90353ba9586cad4555a57db7ef67464/datadog/internal/utils/utils.go#L51-L56

**To Reproduce**

Execute the following command in terraform:

```
$ terraform import datadog_monitor.my_monitor 123456789
# import error-tracking monitor:
# {
#   "restricted_roles": null,
#   "tags": [],
#   "deleted": null,
#   "query": "error-tracking-traces(\"env:staging @issue.age:<=300000\").rollup(\"count\").by(\"@issue.id\").last(\"5m\") > 1",
#   ...
#   "type": "error-tracking alert",
```

**Expected behavior**

Can parse `"type": "error-tracking monitor`

**Environment and Versions (please complete the following information):**

- Terraform v1.0.11
- terraform-provider-datadog v3.9.0
    - github.com/DataDog/datadog-api-client-go v1.10.0

**Additional context**

- Support request
    - https://help.datadoghq.com/hc/en-us/requests/710664
- Pull request attempting to fix the problem (closed)
    - https://github.com/DataDog/datadog-api-client-go/pull/1382

**Comment by therve** [comment]
Fixed in #1395 , thanks.
