### ISSUE TITLE
support muting and unmuting monitors

### ISSUE THREAD

**Issue by rgarcia** [DataDog/datadog-api-client-go#1597]
**Is your feature request related to a problem? Please describe.**
We would like to build some automation around muting and unmuting monitors.

**Describe the solution you'd like**
Support for the mute and unmute api v1 endpoints: 
- https://docs.datadoghq.com/api/latest/monitors/#mute-a-monitor
- https://docs.datadoghq.com/api/latest/monitors/#unmute-a-monitor

**Describe alternatives you've considered**
Not using this library.

**Additional context**
None

**Comment by therve** [comment]
Hi,

Those APIs are not supported anymore, downtimes are now the correct way to mute monitors: https://docs.datadoghq.com/api/latest/downtimes/. Thanks.
