### ISSUE TITLE
README and some examples are out to date

### ISSUE THREAD

**Issue by lplazas** [DataDog/datadog-api-client-go#1605]
**Describe the bug**
The CreateUser example on the README as well as the code under `examples/v2/users/CreateUser.go` seems to be out of date. When you add the dependency to a go mod project, you don't have access to the common package

For maintainer: Please add the documentation tag

**To Reproduce**
On an empty project, run: `go get github.com/DataDog/datadog-api-client-go`
The `common` package is not accessible, rendering the example unusable. 

**Fix**
The example below fixes the README, I can open a PR for that but I wanted to get some context as if the examples are somehow auto generated? I can update those in the PR as well.

```golang
package main

import (
	"context"
	"fmt"
	"github.com/DataDog/datadog-api-client-go/api/v2/datadog"
	"os"
)

func main() {
	ctx := context.WithValue(
		context.Background(),
		datadog.ContextAPIKeys,
		map[string]datadog.APIKey{
			"apiKeyAuth": {
				Key: os.Getenv("DD_CLIENT_API_KEY"),
			},
			"appKeyAuth": {
				Key: os.Getenv("DD_CLIENT_APP_KEY"),
			},
		},
	)

	body := *datadog.NewUserCreateRequest(*datadog.NewUserCreateData(*datadog.NewUserCreateAttributes("jane.doe@example.com"), datadog.UsersType("users")))

	configuration := datadog.NewConfiguration()
	apiClient := datadog.NewAPIClient(configuration)

	resp, r, err := apiClient.UsersApi.CreateUser(ctx, body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating user: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	responseData := resp.GetData()
	fmt.Fprintf(os.Stdout, "User ID: %s", responseData.GetId())
}

```

**Comment by therve** [comment]
The code you mention reflects master, but `go get` uses release AFAICT. `go install github.com/DataDog/datadog-api-client-go@master` will give you the latest code, otherwise https://docs.datadoghq.com/api/latest/ and https://pkg.go.dev/github.com/DataDog/datadog-api-client-go#section-readme use the release versions.

**Comment by lplazas** [comment]
Thank you for the clarification @therve , closing this issue.
