### ISSUE TITLE
SubmitMetrics does not comply with http.Error spec, crashes on any spec-compliant error

### ISSUE THREAD

**Issue by jkopczyn** [DataDog/datadog-api-client-go#1620]
**Describe the bug**
The [http stdlib](https://pkg.go.dev/net/http#Error) has this to say about `http.Error`\*:
> `func Error`
> `func Error(w ResponseWriter, error string, code int)`
> Error replies to the request with the specified error message and HTTP code. It does not otherwise end the request; the caller should ensure no further writes are done to w. **The error message should be plain text.**

However, if you follow this rule for a server which can receive Datadog metrics\*\*, the library will crash if it receives any error generated this way. It expects JSON-formatted error strings and tries to parse any string it receives as JSON; for an error like so:

```http.Error(wr, "Client Error: Headers", http.StatusBadRequest)```

SubmitMetrics fails with the following message:

```level=error msg="invalid character 'C' looking for beginning of value"```

<sub>
*An example of using net/http this way can be viewed at pkg.go.dev/net/http#example-Hijacker</sub>
<br />
<sub> 
**In my case the server is a proxy which lets us limit our client's access-control exceptions to a single URL we control rather than a selection of Datadog-controlled URLs. Code snippets abstract this away but are simplified versions of the real production code.</sub>

**To Reproduce**

1 Create a proxy or other endpoint which accepts HTTP traffic. It can be run anywhere - `localhost:80` is fine. Set the endpoint to return a plain-text error message like the above snippet. (https://gist.github.com/jkopczyn/068fd2edd8d259a94d18e0229030d629 should be sufficient, ignoring the request entirely for brevity.) 
2. Create an instance of the library which directs a `SubmitMetrics` request to that endpoint. Configure the library to submit metrics to a nonstandard URL. (https://gist.github.com/jkopczyn/f9dc116cc4c03b6ccaeee25d9313f902 should be sufficient; the metric body doesn't matter.)
3. Run the server and client locally, watching logs of the client.
4. The `invalid character 'C' looking for beginning of value` message will immediately appear.

**Expected behavior**
All plain-text error messages SHOULD be accepted. Other messages MAY be accepted; ideally they wouldn't be, but that's a breaking change to the API and doesn't seem crucial to do until and unless a new major version of the API is coming out.

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
Go version 1.16 through 1.18 should make no difference here; different parts of the setup use both, and testing code used during development made no effort to match them. This behavior was consistent throughout.

**Comment by jkopczyn** [comment]
I don't see any active `severity/*` labels in this repository or guidelines on how to choose one, so I haven't attempted to add any.

**Comment by therve** [comment]
Hi,

Can you verify which version of the SDK you're using? I think I fixed that in #1572

**Comment by jkopczyn** [comment]
I haven't specified a package version; `go mod tidy` selects `v1.16.0` and the source has `import "github.com/DataDog/datadog-api-client-go/api/v2/datadog"`. Since you mentioned it, I tried switching to `v2.0.0` unsuccessfully. As far as I can tell there's no way to validly specify v2.x in a go.mod file for this repository; it doesn't seem to follow any of the conventions I've been able to find.

**Comment by jkopczyn** [comment]
Found a way to import it, and it has the same problem. Gists are updated, but to explicitly specify packages imported and other config, see <https://github.com/jkopczyn/dd-api-bug-demo/tree/main>. The same error occurs.

**Comment by therve** [comment]
Thanks for the detailed example. I may miss something, but I think the issue comes from the fact that your server returns 200. Because it returns 200, the client tries to parse the response payload (not parse an error), and that is what's failing.

**Comment by jkopczyn** [comment]
It didn't seem to behave well when returning an error, but this example is now fairly far from the real code - the weird versioning is not compatible with our real code without a lot of work - so I'm unsure what the correct behavior is.

**Comment by therve** [comment]
We had a hiccup releasing 2.0, but now things should be settled: we have a common package for client and configuration, and API and models are in their respective datadogVX package,

**Comment by therve** [comment]
I'll close that one for now, feel free to reopen with more information. Thanks,
