### ISSUE TITLE
RUM application API

### ISSUE THREAD

**Issue by JonasBak** [DataDog/datadog-api-client-go#1621]
**Is your feature request related to a problem? Please describe.**

We would like to be able to manage RUM applications through the API, so we can manage RUM applications with terraform (related issue: https://github.com/DataDog/terraform-provider-datadog/issues/1058).
The [documentation](https://docs.datadoghq.com/api/latest/rum/) (and this client) seems to only describe endpoints related to RUM events, not applications.
If the endpoints were documented and added to the client, we could add it to the terraform provider.

**Describe the solution you'd like**

That CRUD endpoints for RUM applications are documented and added to this client (like the `/api/v1/rum/projects` that seems to be used in the portal today).

**Describe alternatives you've considered**

**Additional context**

**Comment by therve** [comment]
Hi,

Support for the v2 endpoint has been merged in #1623 . Thanks!
