### ISSUE TITLE
Review stale PR to unblock issue #1565 for TF Provider for Datadog

### ISSUE THREAD

**Issue by linouk23** [DataDog/datadog-api-client-go#1677]
**Is your feature request related to a problem? Please describe.**
This issue is similar to https://github.com/DataDog/datadog-api-client-go/issues/1621. Namely, there's a feature request for TF Provider for Datadog to add a new resource https://github.com/DataDog/terraform-provider-datadog/issues/1565 which is blocked since CRUD API for managing Confluent Cloud integration is unavailable at the moment.

**Describe the solution you'd like**
It looks like the corresponding PR has been generated already so we'd like someone from @integrations-tools-and-libraries to review & merge it (cc @therve @jirikuncar @zippolyte @nmuesch @skarimo): https://github.com/DataDog/datadog-api-client-go/pull/1648

![image](https://user-images.githubusercontent.com/5459870/190971948-84168d81-bfd9-4131-ac7f-6d3b2855df65.png)

Thanks!

**Comment by therve** [comment]
Thanks. We're on it it should happen soon.

**Comment by linouk23** [comment]
@therve is there any update since last Monday? There're a few customers who are waiting for https://github.com/DataDog/terraform-provider-datadog/issues/1565 to happen.
