### ISSUE TITLE
New v2 CIVisibility api doesn't return an error from a pagination function

### ISSUE THREAD

**Issue by ryanwalls** [DataDog/datadog-api-client-go#1751]
**Describe the bug**
When the `CIVisibilityTestsApi.ListCIAppTestEventsWithPagination` func is called, all errors are swallowed.  

https://github.com/DataDog/datadog-api-client-go/blob/master/api/datadogV2/api_ci_visibility_tests.go#L243-L301

**To Reproduce**

* Run the function with no API credentials, which results in a 403 in the logs.  But no error is returned from the function.

**Expected behavior**
I would expect errors to be caught in the async func and bubbled up to the calling function using channels or some other method.

**Environment and Versions (please complete the following information):**
v2 2.5.0

**Comment by TovRudyy** [comment]
👋🏻 We are looking into it. Definitely the function should return an error at least. Thanks for the heads-up!

**Comment by TovRudyy** [comment]
Issue been addressed in [57f5c918f834db13deb217f2b5a781ce46590d86](https://github.com/DataDog/datadog-api-client-go/commit/57f5c918f834db13deb217f2b5a781ce46590d86). Going to close it 👍🏻
