### ISSUE TITLE
Monthly Usage Attribution API response model does not contain all supported metric types

### ISSUE THREAD

**Issue by krosen040** [DataDog/datadog-api-client-go#1771]
**Describe the bug**
The API response model for the `GetMonthlyUsageAttribution` API does not specify fields for all types of `MonthlyUsageAttributionSupportedMetrics`. For example, the [DBM metrics are supported](https://github.com/DataDog/datadog-api-client-go/blob/2b4ea5d108107e56e71cb40a0d97834ab575ffe2/api/datadogV1/model_monthly_usage_attribution_supported_metrics.go#L41-L44) as request parameters, but the [response model does not contain the corresponding fields](https://github.com/DataDog/datadog-api-client-go/blob/2b4ea5d108107e56e71cb40a0d97834ab575ffe2/api/datadogV1/model_monthly_usage_attribution_values.go#L12).

**To Reproduce**
Call the `GetMonthlyUsageAttribution` API using `datadogV1.MONTHLYUSAGEATTRIBUTIONSUPPORTEDMETRICS_DBM_HOSTS_USAGE` as the `fields` parameter.

**Expected behavior**
The `MonthlyUsageAttributionResponse` struct should contain the DBM host data, but doesn't due to the field missing.

**Environment and Versions (please complete the following information):**
`github.com/DataDog/datadog-api-client-go/v2 v2.5.0`

**Comment by therve** [comment]
Should be fixed by #1776. Thank you!
