### ISSUE TITLE
DataDog Synthetics API Assertion Operator for Matches Regex and Does Not Match Regex

### ISSUE THREAD

**Issue by pbpblush** [DataDog/datadog-api-client-go#1827]
**Note:**
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked.

<img width="205" alt="Screenshot 2023-01-13 at 11 08 41 AM" src="https://user-images.githubusercontent.com/61514105/212399375-7de40b55-7528-4fb8-b000-d13e6374de60.png">

**Is your feature request related to a problem? Please describe.**
The problem is that not all manually created tests are portable to programatic test creation by use of platforms like Terraform or frameworks like Python. The API should handle ALL cases available on the Web UI.

**Describe the solution you'd like**
Add the following operators

```
SYNTHETICSASSERTIONOPERATOR_MATCHES_REGEX        SyntheticsAssertionOperator = "matchesRegex"
SYNTHETICSASSERTIONOPERATOR_DOES_NOT_MATCH_REGEX SyntheticsAssertionOperator = "doesNotMatchRegex"
```

**Describe alternatives you've considered**
There is no way to programatically add this type of assertion operator without the DataDog API. The online documentation does not clearly outline what operator values are available to use. I had to read through this code base. I also don't see unit tests for Regex.

**Additional context**
A potential test data would be:

```
{
  type     = "body"
  operator = "validatesJSONPath"
  target   = {
    jsonpath    = "$.PhoneNumber"
    operator    = "matchesRegex"
    targetvalue = "\d+"
  }
}
```

**Comment by nkzou** [comment]
Hi there, thanks for reaching out! For matching Regex, I believe the corresponding operator value in the API Client/terraform is called "matches" and "doesNotMatch". Let us know if this works for you, and reopen this issue if not. Thanks!

**Comment by pbpblush** [comment]
Hi there,

You are correct. My mistake!
