### ISSUE TITLE
GetUsageBillableSummary returns nil ApplicationSecurityHostTop99

### ISSUE THREAD

**Issue by keithmcdonald-shopify** [DataDog/datadog-api-client-go#1915]
**Describe the bug**

The `GetUsageBillableSummary` function does not return the correct value for the `ApplicationSecurityHostTop99` field. It appears to be due to a bug on the following line:

https://github.com/DataDog/datadog-api-client-go/blob/master/.generator/schemas/v1/openapi.yaml#L15448

The field name is missing the 'p' on the end. It should be `application_security_host_top99p` rather than `application_security_host_top99`.

**To Reproduce**

1. Call the `GetUsageBillableSummary` function against an account that monitors application security hosts.
2. Read the `UsageBillableSummaryHour` field from the `UsageBillableSummaryResponse`.
3. Read the `UsageBillableSummaryKeys` field from the `UsageBillableSummaryHour`.
4. Read the `ApplicationSecurityHostTop99` field from the `UsageBillableSummaryKeys`.

**Expected behavior**
The `ApplicationSecurityHostTop99` field is a non-nil `*UsageBillableSummaryBody`.

**Actual behavior**
The `ApplicationSecurityHostTop99` field is nil.

**Screenshots**
Postman screenshot showing the response of the `billable-summary` API includes the 'p' on the end of application_security_host_top99p:
![image](https://user-images.githubusercontent.com/113645525/226525115-0ce8c94a-275b-46b9-a320-e32a484abdb3.png)

**Environment and Versions (please complete the following information):**
A DataDog account that uses application security hosts.

**Comment by therve** [comment]
Fixed in #1916 , will be released next month. Thanks a lot for your report.
