### ISSUE TITLE
Missing pagination support for SearchIncidents method

### ISSUE THREAD

**Issue by djowinz-pp** [DataDog/datadog-api-client-go#1922]
**Describe the bug**
The SearchIncidents API method supports pagination but is not properly exposed through the DataDog go, client. It's also not present in the documentation on the website.

**To Reproduce**

1. Submit cURL request to API
```
# Required query arguments
export query="CHANGE_ME"
curl -X GET "https://api.datadoghq.com/api/v2/incidents/search?query=${query}" \
-H "Accept: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}"
```

2. Add the pagination parameters page[size] & page[offset]
```
export query="CHANGE_ME"
curl -X GET "https://api.datadoghq.com/api/v2/incidents/search?query=${query}&page[size]=1&page[offset]=0" \
-H "Accept: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}"
```

3. See that pagination support is possible for the SearchIncidents endpoint.

**Expected behavior**
The apiSearchIncidentsRequest should include both page[size] & page[offset] parameters similar to apiListIncidentsRequest since both endpoints support pagination.

**Screenshots**
![Screenshot 2023-03-27 at 5 43 43 PM](https://user-images.githubusercontent.com/93112712/228083813-579626b9-8b77-4ab9-bac3-9c4e32d55aac.png)

**Environment and Versions (please complete the following information):**
Production Datadog instance, version 2.11.0 of the datadog-api-client-go package.

**Comment by therve** [comment]
Fixed in #1923 , thanks!
