### ISSUE TITLE
Exponential complexity in JSON parsing logic

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-api-client-go#2055]
The changes introduced in https://github.com/DataDog/datadog-api-client-go/pull/926 made the JSON parsing algorithm's complexity exponential in the depth of the nesting of the parsed JSON object.

The model structs implement `json.Unmarshaler`. The `UnmarshalJSON` is generated by [this template](https://github.com/DataDog/datadog-api-client-go/blob/37c564ed2b77209f7dfd51f94684f20a7c2a2732/.generator/src/generator/templates/model_simple.j2#L329). The `json.Unmarshal` func on the original byte slice is called at least twice: once to deserialize into the `required` variable, and once to deserialize into the `all` variable. Both of these variables have the model structs in them...

Objects with a lot of nesting like e.g. large Dashboards with multiple groups demonstrate this really well. This benchmark shows how unmarshalling a single dashboard takes over 5 seconds using model types vs. 3ms when unmarshalling into a `map[string]any`:
```
$ go test -benchtime 1m -bench .
goos: linux
goarch: amd64
pkg: go.indeed.tech/tmi/datadog-snapshot-downloader/internal/content
cpu: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
BenchmarkDatadogModels-8   	      12	5755656561 ns/op	600623150 B/op	11279345 allocs/op
BenchmarkJSONParsing-8                 	   21346	   3262194 ns/op	  664023 B/op	   15466 allocs/op
PASS
ok  	go.indeed.tech/tmi/datadog-snapshot-downloader/internal/content	281.310s
```

Benchmark code (the test data is a 300kb-long dashboard json dumped using the get dashboard API):
```
func BenchmarkDatadogModels(b *testing.B) {
	b.ReportAllocs()
	jb, err := os.ReadFile("/home/sergey/indeed/datadog-snapshot-downloader/v9n-bbq-bgv.txt")
	if err != nil {
		b.Fatal(err.Error())
	}
	for i := 0; i < b.N; i++ {
		var db datadog.Dashboard
		err := json.Unmarshal(jb, &db)
		if err != nil {
			b.Fatal(err.Error())
		}
	}
}

func BenchmarkJSONParsing(b *testing.B) {
	b.ReportAllocs()
	jb, err := os.ReadFile("/home/sergey/indeed/datadog-snapshot-downloader/v9n-bbq-bgv.txt")
	if err != nil {
		b.Fatal(err.Error())
	}
	for i := 0; i < b.N; i++ {
		var db map[string]any
		err := json.Unmarshal(jb, &db)
		if err != nil {
			b.Fatal(err.Error())
		}
	}
}
```

**Comment by therve** [comment]
Thanks for your report. This code is indeed uselessly complicated. I tried something in the attached PR, would you mind running your benchmark to see if that makes a difference? Thanks.

**Comment by deadok22** [comment]
Hey @therve! 

Thanks for the quick turnaround! 

I took a look at the patch and it looks good. It definitely does remove the exponential complexity, so I'd expect it to work on par with the `map[string]any` version, if not faster because the strings representing the field names will not need to be allocated.

I'll run my benchmarks with the new code tomorrow.

**Comment by deadok22** [comment]
Hm, it's 10 times faster, but still much slower than `map[string]any`.

```
$ go test -benchtime 1m -bench .
goos: linux
goarch: amd64
pkg: github.com/DataDog/datadog-api-client-go/v2/bench
cpu: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
BenchmarkDatadogModels-8   	     139	 555087941 ns/op	49101125 B/op	 1066622 allocs/op
BenchmarkJSONParsing-8     	   22042	   4497668 ns/op	  664013 B/op	   15466 allocs/op
PASS
ok  	github.com/DataDog/datadog-api-client-go/v2/bench	261.373s
```

**Comment by deadok22** [comment]
Ah, there's this `json.Unmarshal` call to parse `additionalProperties`...

**Comment by deadok22** [comment]
Here's a prototype for a single-pass parser for both known fields and unknown fields. Writing a template for the `unmarshalJSONObject` call should be fairly straightforward.

```
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

func main() {
	knownData := struct {
		A1 struct{ B1 int }
	}{}

	additionalProperties := make(map[string]any, 0)

	err := unmarshalJSONObject(
		[]byte(`{"a1": {"b1": 42}, "a2": "whee"}`),
		map[string]any{
			"a1": &knownData.A1,
		},
		additionalProperties,
	)
	if err != nil {
		panic(err.Error())
	}

	fmt.Printf("knownData: %v\n", knownData)
	fmt.Printf("additionalProperties: %v\n", additionalProperties)
}

func unmarshalJSONObject(
	from []byte,
	knownFieldPointers map[string]any,
	unknownFields map[string]any,
) error {
	decoder := json.NewDecoder(bytes.NewReader(from))
	t, err := decoder.Token()
	if err != nil {
		return err
	}
	if t != json.Delim('{') {
		//TODO make an error identical to what encoding/json would return
		return errors.New("expected an object")
	}

	for {
		t, err = decoder.Token()
		if err != nil {
			return err
		}

		if t == json.Delim('}') {
			break
		}

		key, ok := t.(string)
		if !ok {
			//TODO make an error identical to what encoding/json would return
			return errors.New("expected an object")
		}

		if fPtr, knownField := knownFieldPointers[key]; knownField {
			err := decoder.Decode(fPtr)
			if err != nil {
				return err
			}
		} else {
			var v any
			err := decoder.Decode(&v)
			if err != nil {
				return err
			}
			unknownFields[key] = v
		}
	}

	//TODO err out if the input was not fully read

	return nil
}

```

Playground link: https://go.dev/play/p/_DD7L4GH_RI

**Comment by therve** [comment]
I believe the remaining performance hit is inherent to how UnmarshalJSON works with models, as you end up calling it on each field type. There is an impact of the additionalProperties call but I suspect small: as you noticed raw unmarshal is pretty fast.
The alternative would be to have an API with "raw" data returned, but I'm not sure how useful that would be.

**Comment by deadok22** [comment]
The `json.Unmarshal` call for `additionalProperties` contributes an additional linear amount of work done on every level of recursion. I.e. a leaf object field gets parsed 1 + its depth times. The overhead is by no means small. In the benchmark I shared earlier parsing a _single_ dashboard takes *over half a second* of CPU time.

Let's have a look at an example and see how many times a leaf node gets parsed:
```
type Model1 struct {
	Model2 Model2
}
type Model2 struct {
	Model3 Model3
}
type Model3 struct {
	Model4 Model4
}
type Model4 struct {
	Leaf string `json:"leaf"`
}
```
The call tree for parsing `Model1` looks something like this:
```
Model1.UnmarshalJSON
	Model2.UnmarshalJSON
		Model3.UnmarshalJSON
			Model4.UnmarshalJSON
				json.Unmarshal (leaf)
				json.Unmarshal(map[string]interface{})
					...
					json.Unmarshal (leaf)
			json.Unmarshal(map[string]interface{})
				...
				json.Unmarshal (leaf)
		json.Unmarshal(map[string]interface{})
			...
			json.Unmarshal (leaf)
	json.Unmarshal(map[string]interface{}) (model1)
		...
		json.Unmarshal (leaf)
```
The `leaf` field in the example above is parsed 5 times (1 + its depth). 

The prototype I shared parses everything once: the depth of nesting doesn't affect the computational complexity.

**Comment by therve** [comment]
Getting rid of the additionalProperties unmarshal completely gives me a 25% gain on your benchmark, which is nice but not much compared with the 1500% of the patch attached. I think we'll merge this one and see later if the additional complexity of a custom parser is worth it. I don't think a single pass is possible considering the validation logic we have in model, but we'll investigate.
