### ISSUE TITLE
Timeseries widget with event overlay has `UnparsedObject`

### ISSUE THREAD

**Issue by tmonck** [DataDog/datadog-api-client-go#2088]
**Describe the bug**
A timeseries widget that has an overlay can't properly parse and ends up with `UnparsedObject` being populated. 

Label the issue properly.

- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
Setup:
1. Go to Create Dashboard in the Web application
2. Click on Add Widgets or Powerpacks
3. Select Time Series
4. Expand "Event Overlays" section
5. Click "Add Event Overlay"
6. Click the Save button.

Reproducing issue in SDK.
If you make a get request using this SDK, the newly created dashboard will have `UnparsedObject` which breaks the terraform provider.
Some sample code that will allow you to see the issue is below. I have left out all the setup pieces.

```
configuration := datadog_lib.NewConfiguration()
apiClient := datadog.NewAPIClient(configuration)
api := datadogV1.NewDashboardsApi(apiClient)
resp, r, err := api.GetDashboard(ctx, "DASHBOARD_ID")
if err != nil {
	fmt.Fprintf(os.Stderr, "Error when calling `DashboardsApi.GetDashboard`: %v\n", err)
	fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
}
for _, widget := range resp.Widgets {
	if unparsed_widget, _ := datadog_lib.ContainsUnparsedObject(widget); unparsed_widget {
		fmt.Printf(fmt.Sprintf("Widget: %d had unparsed elements\n", widget.GetId()))
		for _, request := range widget.Definition.TimeseriesWidgetDefinition.Requests {
			if unparsed_request, _ := datadog_lib.ContainsUnparsedObject(request); unparsed_request {
				fmt.Printf(fmt.Sprintf("Request with display_type: %s had unparsed elements\n", request.DisplayType))
				fmt.Printf("Invalid Display Type\nAllowedTypes are:\n")
				for _, allowedType := range request.DisplayType.GetAllowedValues() {
					fmt.Println(fmt.Sprintf("%s", allowedType))
				}
			}
		}
	}
}
```

**Expected behavior**
I would expect the SDK to be able to properly parse the dashboards and allow all of the `display_types` possible

**Screenshots**

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:

- github.com/DataDog/datadog-api-client-go/v2 v2.14.0

**Additional context**

**Comment by nkzou** [comment]
Hi, thanks for the report. This will be fixed in the next release with #2096 , and the corresponding terraform PR is https://github.com/DataDog/terraform-provider-datadog/pull/2006
