### ISSUE TITLE
Typo in ServiceDefinitionV2Dot2 struct

### ISSUE THREAD

**Issue by kgsharp** [DataDog/datadog-api-client-go#2264]
There is a typo here, "Langauges" instead of "Languages". The result is that it is throws the following on the DataDog side when used:

"additionalProperties 'langauges' not allowed"

https://github.com/DataDog/datadog-api-client-go/blame/e1e0f74c3fd21b7a2122559a3268277b489a502b/api/datadogV2/model_service_definition_v2_dot2.go#L513

**Comment by therve** [comment]
Thanks, fixed in #2266
