### ISSUE TITLE
Add CI pipeline fingerprints field in Service Catalog definition V2.2

### ISSUE THREAD

**Issue by dgdelahera** [DataDog/datadog-api-client-go#2414]
The Datadog go client [V2.2 schema](https://github.com/DataDog/datadog-api-client-go/blob/26298c47b918e8bf360090355685fb326f9d4831/api/datadogV2/model_service_definition_v2_dot2.go#L14) doesn't match the actual [schema](https://github.com/DataDog/schema/blob/main/service-catalog/v2.2/schema.json#L127C16-L127C28). The field `ci-pipeline-fingerprints` is missing

**Comment by skarimo** [comment]
Thanks for opening the issue. This is resolved by https://github.com/DataDog/datadog-api-client-go/pull/2432 and will be included in the next release.
