### ISSUE TITLE
Noise log: Using unstable operation

### ISSUE THREAD

**Issue by jwillker** [DataDog/datadog-api-client-go#2538]
**Is your feature request related to a problem? Please describe.**

There are a warn log when using unstable API right here: https://github.com/DataDog/datadog-api-client-go/blob/535a952ec44470ef4d460664a90d1c3eabc42f93/api/datadog/configuration.go#L519

My integration make a lot of requests to DataDog API, and I end up with a lot of logs like this:

```log
2024/06/19 12:18:21 WARNING: Using unstable operation 'v2.QueryTimeseriesData'
```

**Describe the solution you'd like**

I would like a way to disable this message.

**Comment by jwillker** [comment]
Not stale

**Comment by skarimo** [comment]
Thanks for the issue. We have downgraded the log to debug in https://github.com/DataDog/datadog-api-client-go/pull/2780. Closing this issue.
