### ISSUE TITLE
Many documented api_client.MetricsApi.*(...).Execute() have more arguments that needed

### ISSUE THREAD

**Issue by Vincoll** [DataDog/datadog-api-client-go#350]
**Describe the bug**
Documentation issue :  
Many api_client.MetricsApi.*(...).Execute() have more arguments that needed  
https://github.com/DataDog/datadog-api-client-go/blob/master/api/v1/datadog/docs/MetricsApi.md

Eg : 
`resp, r, err := api_client.MetricsApi.QueryMetrics(ctx, from, to, query).Execute()`  

Where `(a *MetricsApiService) QueryMetrics` takes only a `_context.Context` arg.
https://github.com/DataDog/datadog-api-client-go/blob/2971fd4762f956f58df55ca2b85e47c3fb7204a2/api/v1/datadog/api_metrics.go#L532

**To Reproduce**
1. Go to https://github.com/DataDog/datadog-api-client-go/blob/master/api/v1/datadog/docs/MetricsApi.md
2. Check references to `api_client.MetricsApi.*(...).Execute()`
  * ListActiveMetrics
  * MetricsApi
  * QueryMetrics
  * ...
3. See too many args

**Expected behavior**
That the documentation reflects the implemented code

**Comment by jirikuncar** [comment]
@Vincoll thank you for reporting this issue. I think it's coming from the upstream template https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go-experimental/api_doc.mustache#L42.

**Comment by Vincoll** [comment]
Indeed,
As you may know, this documentation is also present in the (updated) DD API Documentation front page. 
https://docs.datadoghq.com/fr/api/v1/metrics/

Leading to a "not so great" first user experience for the Go API :/

**Comment by zippolyte** [comment]
Fixed in #473
