### ISSUE TITLE
Support for Synthetics CI trigger endpoints

### ISSUE THREAD

**Issue by dougnukem** [DataDog/datadog-api-client-go#356]
**Note:**

**Is your feature request related to a problem? Please describe.**
I'd like to use the Go library to trigger and poll the results of Synthetic CI tests:
- https://github.com/DataDog/documentation/blob/e14faec768723b78006d44cdf99bb335fb4286b5/content/en/synthetics/ci.md

It appears that API code is updated from a repo:
- https://github.com/DataDog/datadog-api-spec/pull/451

(But I don't believe that's a public repository to open a pull-request for)

**Describe the solution you'd like**
Support API spec updates to generate Go code to support the following endpoints:
- https://github.com/DataDog/documentation/blob/e14faec768723b78006d44cdf99bb335fb4286b5/content/en/synthetics/ci.md

**Comment by dougnukem** [comment]
Not sure the right way to contribute/open a PR for the datadog-api-spec repo:
- https://github.com/supply-drop/datadog-api-client-go/commit/a825a993c4caa67b73987bf9360f3786d4c3aaaf#diff-13d8957c539d429b92c59980a6539cd2

**Comment by therve** [comment]
Hi Doug. Contributions to the spec repository are kept internal at least for now. This particular endpoint is in private beta, so in different situation. The team wants additional time to be allow to make changes if necessary, and will publish the spec when ready. Thanks for your patience.

**Comment by therve** [comment]
I believe this has been available for a while. Let me know if that doesn't work for you, thanks.
