### ISSUE TITLE
GetUsageTopAvgMetrics not accepting month param

### ISSUE THREAD

**Issue by jumbosushi** [DataDog/datadog-api-client-go#472]
**Describe the bug**

I used the example code from [`GetUsageTopAvgMetrics`](https://github.com/DataDog/datadog-api-client-go/blob/master/api/v1/datadog/docs/UsageMeteringApi.md#getusagetopavgmetrics), but seeing the following error:

```
./main.go:30:67: too many arguments in call to api_client.UsageMeteringApi.GetUsageTopAvgMetrics
        have (context.Context, time.Time)
        want (context.Context)
``` 

**To Reproduce**
1. Go to [`GetUsageTopAvgMetrics`](https://github.com/DataDog/datadog-api-client-go/blob/master/api/v1/datadog/docs/UsageMeteringApi.md#getusagetopavgmetrics) and copy the example code as `main.go`
2. Update `DD_CLIENT_API_KEY`, `DD_CLIENT_APP_KEY`
3. Replace `"Get-Date"` string with `time.Now()`
4. Run `go run main.go`

**Expected behavior**
Run without an error

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - macOS Mojave v10.14.6
  - `go version go1.14.2 darwin/amd64`

**Comment by zippolyte** [comment]
fixed in #473
