### ISSUE TITLE
Support for Post Event endpoint

### ISSUE THREAD

**Issue by ryndaniels** [DataDog/datadog-api-client-go#514]
My team would like to use the go library to post events to the event stream. However, it seems that the [post method](https://docs.datadoghq.com/api/v1/events/#post-an-event) is missing. Is there any estimated timeframe for when support for this might be added? Thanks!

**Comment by therve** [comment]
Thanks for your report. We don't have a timeframe or whether it's going to actually happen. I suggest using https://github.com/zorkian/go-datadog-api for that particular use case for now.

**Comment by edigaryev** [comment]
Any idea why this was closed?

The [`EventsApi`](https://pkg.go.dev/github.com/DataDog/datadog-api-client-go/v2/api/datadogV2#EventsApi) still doesn't seem to support the [Post an event](https://docs.datadoghq.com/api/latest/events/#post-an-event) endpoint.

**Comment by therve** [comment]
This is supported on the v1 endpoint: https://datadoghq.dev/datadog-api-client-go/pkg/github.com/DataDog/datadog-api-client-go/v2/api/datadogV1/#EventsApi.CreateEvent
