### ISSUE TITLE
Examples shown in docs will result in "ctx declared but not used"

### ISSUE THREAD

**Issue by max-rocket-internet** [DataDog/datadog-api-client-go#547]
**Describe the bug**

Take the most basic example, to validate an API key: https://github.com/DataDog/datadog-api-client-go/blob/master/api/v1/datadog/docs/AuthenticationApi.md#example

`ctx` is not used and will result in error `ctx declared but not used`.

I can guess that `ctx` is supposed to be used in place of `context.Background()` but is this really good documentation, for every single example in this repo and on [docs.datadoghq.com/api/v1](https://docs.datadoghq.com/api/v1)?

**Expected behavior**

Example that is ready to be copy, pasted and work without error 🙂

**Comment by therve** [comment]
Hi, this has been fixed in your repo, should be pushed to the doc website shortly. Thanks.
