### ISSUE TITLE
How to validate API key with EU site?

### ISSUE THREAD

**Issue by max-rocket-internet** [DataDog/datadog-api-client-go#548]
**Describe the bug**

Some [of this repo](https://github.com/DataDog/datadog-api-client-go/blob/master/tests/api/v1/datadog/features/authentication.feature#L8) states:

> set the environment variable  `DATADOG_HOST` to `https://api.datadoghq.eu` or override this value  directly when creating your client.

Setting `DATADOG_HOST` doesn't work for me. Where/how can I set the host when creating my client?

**Expected behavior**

Clear and concise documentation on how to use EU DD host.

**Comment by therve** [comment]
Hi. We dont' support env variables in our SDK directly. To use EU you can do something like that for example:

```
    ctx = context.WithValue(ctx, datadog.ContextServerVariables, map[string]string{
                "site": "datadoghq.eu",
    })
```

Let us know if that works for you.

**Comment by max-rocket-internet** [comment]
OK thank you @therve
