### ISSUE TITLE
OpenAPI definition lacks the Submit Metrics endpoint.

### ISSUE THREAD

**Issue by jgandt-marq** [DataDog/datadog-api-client-go#692]
**Describe the bug**
The OpenAPI definition for the [Submit Metric](https://docs.datadoghq.com/api/latest/metrics/#submit-metrics) datadog API endpoint is missing. Given this missing endpoint, it appears that one cannot submit metrics using this API client.

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
1. Navigate to the documentation for [Submit Metric](https://docs.datadoghq.com/api/latest/metrics/#submit-metrics) and observe that it is a documented endpoint.
1. Navigate to [API v1 openapi.yml](https://github.com/DataDog/datadog-api-client-go/blob/master/api/v1/datadog/api/openapi.yaml) and observe that the Submit Metric endpoint is not described.
1. Navigate to [API v2 openapi.yml](https://github.com/DataDog/datadog-api-client-go/blob/master/api/v2/datadog/api/openapi.yaml) and observe that the Submit Metric endpoint is not described (expected as the Submit metric endpoint is a V1 endpoint.)

**Expected behavior**
First I expect the https://docs.datadoghq.com/api/latest documentation to match the openapi description. Thus, I expect to find the Submit Metric endpoint listed as a viable endpoint in the openapi config. It is concerning that the documentation does not match the openapi.

If there is an alternative to the Submit Metric, I would expect that to be called out in https://docs.datadoghq.com/api/latest. If this is an intentional omission, I would similarly expect that to be called out, both in the documentation and in the OpenApi definition (I don't know if the latter is actually possible.)

**Screenshots**
N/A

**Environment and Versions (please complete the following information):**
My plan was to submit metrics to datadog when users execute actions from a binary cli on end-user machines. Thus running a datadog agent on an end user machine (internal to the company) is prohibitive and seems like overkill.

**Additional context**
N/A

**Comment by therve** [comment]
Hi,

This is indeed an intentional omission. You can find the OpenAPI spec used by documentation here: https://github.com/DataDog/documentation/blob/master/data/api/v1/full_spec.yaml. We're in the process of clarifying the situation, but that will most likely involve a new library. 

Short term, you can use the community project at https://github.com/zorkian/go-datadog-api to submit metrics. I hope we'll have a better solution to offer soon.

Thanks.

**Comment by jgandt-marq** [comment]
Amazing! Thank you!

Sorry I'm new to OpenAPI and just learning how to read specs. I also didn't realize the documentation had it's own public repo and OpenAPI spec.

I'm excited to see the progress you make!

Feel free to close this issue or leave it open as breadcrumbs for others.

Thanks again.

**Comment by JAicewizard** [comment]
Could you elaborate on why the metrics API is not available in the library, and why it would require a new one?

**Comment by joshk0** [comment]
I'm sure it's probably something like:

* Datadog's revenue model is based on people installing agents and paying a per agent cost.
* The advent of serverless computing is decreasing the need for people to have datadog agents at all. In fact, I've run several Datadog tenants with no agent at all, at this point.
* Sure the metrics endpoint exists, but the point of making it not easily accessible is to make sure as many people as possible stick with the agent based revenue model for just a bit longer.
* Probably, technology leadership at Datadog is aware of this and is retooling pricing, endpoints, etc etc around the new reality, and that will happen soon. In the meantime, the status quo has to be the way it is 🙉

**Comment by therve** [comment]
I hope we do make the metric endpoint easily accessible: https://docs.datadoghq.com/api/latest/metrics/#submit-metrics

The reason it's missing from the generated clients is that it's present in the existing libraries like datadogpy and dogapi-rb, and we need to define where things live in the future.

**Comment by JAicewizard** [comment]
Is this on the roadmap soon-ish? The docs for this repo are very good, while for other library linked above is practically unusable without a deep-dive. It would be very nice to have it available in this library as well, the docs are already there just not the implementation.

**Comment by therve** [comment]
Yes, this is on the roadmap. We're very close to finalizing the details, I'll make sure to keep you updated as soon as the plan is official.

**Comment by joshk0** [comment]
still a thing

**Comment by webercoder** [comment]
Just noticed that #834 added `SubmitMetrics` and `CreateEvent` methods. Any idea when those will make it into a release? I'm just trying to gauge if it's worth waiting vs. using https://github.com/zorkian/go-datadog-api. Thanks.

**Comment by jaredledvina** [comment]
I did not mean to close this issue. Sorry about that.

**Comment by jirikuncar** [comment]
It was released in https://github.com/DataDog/datadog-api-client-go/releases/tag/v1.0.0-beta.19
