### ISSUE TITLE
Add hasExtendedTitle support for security monitoring rule

### ISSUE THREAD

**Issue by bendehaan** [DataDog/datadog-api-client-go#740]
**Note:**
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked.

**Is your feature request related to a problem? Please describe.**
The DataDog Security monitoring rule API includes the `hasExtendedTitle` field. This is not reflected by the client package, and thus can't be implemented in the DataDog Terraform provider right now. This blocks us from using the Security monitoring rule resource in the DataDog Terraform provider, relying on a third party REST API provider instead.

**Describe the solution you'd like**
Support the field in the client API.

**Describe alternatives you've considered**
Use a different client.

**Additional context**
![image](https://user-images.githubusercontent.com/53901866/108711295-6d183c80-7515-11eb-9947-b3c708f61ef6.png)

**Comment by cecileguyon** [comment]
Hi Ben! 
Indeed this field is missing from API, I'll add support for it. 
However, this field has been present for a long time, how come it was noticed this time? (new tests?)

**Comment by bendehaan** [comment]
@cecileguyon Thanks 🙂. I was manually playing around with Insomnia to figure out whether all the settings I expected were being passed correctly outside of Terraform.

**Comment by therve** [comment]
Hi,

This was fixed with #998 . Thank you.
