### ISSUE TITLE
GetSLOHistory cannot unmarshal when using optional target param

### ISSUE THREAD

**Issue by dmartin35** [DataDog/datadog-api-client-go#951]
**Describe the bug**
Making a `apiClient.ServiceLevelObjectivesApi.GetSLOHistory`call with the optional `target` returns an error when unmarshaling: `custom is not a valid SLOTimeframe`

using the api v1 client
```
import datadog "github.com/DataDog/datadog-api-client-go/api/v1/datadog"
```

**To Reproduce**
Using this snippet, 
```
sloId := "a04..."
target := float64(65)

to := time.Now()
from := to.Add(-time.Hour * 24 * 7)

ctx := datadog.NewDefaultContext(context.Background())

configuration := datadog.NewConfiguration()
configuration.SetUnstableOperationEnabled("GetSLOHistory", true)

optionalParams := datadog.GetSLOHistoryOptionalParameters{
Target: &target,
}

apiClient := datadog.NewAPIClient(configuration)
resp, _, err := apiClient.ServiceLevelObjectivesApi.GetSLOHistory(
ctx, sloId, from.UTC().Unix(), to.UTC().Unix(), optionalParams)
if err != nil {
  fmt.Println("error:", err)
}
```
error: output error message is:
```
custom is not a valid SLOTimeframe
```

Unmarshaling is failing at https://github.com/DataDog/datadog-api-client-go/blob/ee806b3ba69c99e89db25765381d56b2ba24fc48/api/v1/datadog/api_service_level_objectives.go#L1077-L1082

**Expected behavior**
I expect the function to be able to unmarshal and return data

**Environment and Versions (please complete the following information):**
- golang 1.16
- github.com/DataDog/datadog-api-client-go v1.0.0-beta.22

**Additional context**
Making the same query from curl/postman produces valid json

Looking at the json result, I saw a new entry in `thresholds`:
```
"thresholds": {
            "7d": {
                "warning": 97.0,
                "warning_display": "97.",
                "target": 95.0,
                "target_display": "95.",
                "timeframe": "7d"
            },
            "30d": {
                "target": 89.99,
                "target_display": "89.99",
                "timeframe": "30d"
            },
            "custom": {
                "target": 65.0,
                "target_display": "65.",
                "timeframe": "custom"
            }
        },
```

where a `timeframe` value is a string "custom". This is probably causing the error when unmarshaling into the `SLOThreshold` struct

https://github.com/DataDog/datadog-api-client-go/blob/ee806b3ba69c99e89db25765381d56b2ba24fc48/api/v1/datadog/model_slo_threshold.go#L17-L22

where "custom" is not a valid value for the `allowedSLOTimeframeEnumValues ` enum
https://github.com/DataDog/datadog-api-client-go/blob/ee806b3ba69c99e89db25765381d56b2ba24fc48/api/v1/datadog/model_slo_timeframe.go#L26-L30

**Comment by therve** [comment]
Fixed by #1017
