### ISSUE TITLE
Missing fields in MetricQueryMetadata struct

### ISSUE THREAD

**Issue by arjunmahishi** [DataDog/datadog-api-client-go#970]
**Describe the bug**
There are a couple of fields missing in the `MetricQueryMetadata` struct. These are also missing in the documentation. 

Here is the actual response I am getting from the `GET /api/v1/query` endpoint:

```json
{
    "end": 1622526239000,
    "attributes": {},
    "metric": "custom.load.1",
    "interval": 120,
    "tag_set": [
        "key1:tag1"
    ],
    "start": 1622504760000,
    "length": 96,
    "query_index": 0,
    "aggr": null,
    "scope": "key1:tag1",
    "pointlist": [
    ],
    "expression": "custom.load.1{key1:tag1}",
    "unit": null,
    "display_name": "custom.load.1"
}
```

As you can see these fields are missing from the struct and the documentation:
- attributes
- tag_set
- query_index

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - version for this project in use: `v1.0.0-beta.22`

**Comment by hydrosquall** [comment]
@arjunmahishi thanks for the report, we've added documentation for `tag_set` and `query_index` in https://github.com/DataDog/datadog-api-client-go/pull/979 . 

The `attributes` field is more complex (when populated, it contains fields that are populated by certain `expression` types that are subject to change). We'll looking into it separately.

**Comment by arjunmahishi** [comment]
Thanks! :)
