### ISSUE TITLE
Can't import module without pulling in unwanted test dependencies

### ISSUE THREAD

**Issue by mrwonko** [DataDog/datadog-api-client-go#989]
As an end-user, I'm interested in packages `github.com/DataDog/datadog-api-client-go/api/v1/datadog` and `github.com/DataDog/datadog-api-client-go/api/v2/datadog`, which have pleasantly few external dependencies. However, the go.mod also contains many undesirable additional dependencies needed by `github.com/DataDog/datadog-api-client-go/tests/...`, which are not actually needed to use the library, just to test it.

Please create a separate go module for the test packages to isolate their dependencies. Look at the go.mod file of gopls for an example:

Its development version uses `replace` to refer to the containing module:

```
module golang.org/x/tools/gopls
go 1.16
require (
    // ...
	golang.org/x/tools v0.1.0
    // ...
)
replace golang.org/x/tools => ../
```

While release versions use an exact version instead:

```
module golang.org/x/tools/gopls
go 1.16
require (
    // ...
	golang.org/x/tools v0.1.1-0.20210504170620-03ebc2c9fca8
    // ...
)
```

This way users e.g. don't need to use a release candidate of dd-trace-go.

**Comment by zippolyte** [comment]
Thanks for the suggestion. We've implemented that in https://github.com/DataDog/datadog-api-client-go/pull/990
Hope that works for you
